---
title: "EDA"
author: "Anandu R"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages/Libraries
```{r}
suppressMessages(
  {
    library(ggplot2)
    library(dplyr)
    library(leaflet)
    library(caret)
    library(glmnet)
  }
)
```

## Data
```{r}
data = read.csv("../beijing.csv"); dim(data)
```

```{r}
head(data)
```

```{r}
names(data)
```

### Unique districts in the dataset
```{r}
length(unique(data$district))
```

### Missing values 
```{r}
temp = sapply(data, function(x){sum(is.na(x))})
temp[as.numeric(which(temp>0))]
```

### Unique values in each columns
```{r}
temp = sapply(data, function(x){length(unique(factor(x)))})
temp[as.numeric(which(temp>0))]
```

## Distribution of price in each regions
```{r}
ggplot(data, 
       aes(y = price, x = factor(district), fill = factor(district))
      ) + geom_bar(stat = "identity") 
```

## Map view of districts
```{r results='asis'}
## Subsetting data for mapplot
data_mp = select(data, select = c(Lat, Lng, district))
names(data_mp) = c("lat","lng", "district")

data_mp %>% 
    leaflet() %>%
    addTiles() %>%
    addMarkers(clusterOptions = markerClusterOptions()) 
```  


```{r}
g = data %>% 
  group_by(district, subway) %>%
  summarise(
    price = median(price)/10e3
  ) %>%
  ggplot(aes(x = district,
             y = price)
         ) + 
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) + 
  scale_y_continuous(name="Price (in K)") + 
  scale_x_discrete(name="District") 
g
```

```{r}
data_cleaned = read.csv("../Datacleaning/cleaned_beijing.csv")
data_cleaned_sampled = data_cleaned[sample(10000),]
dim(data_cleaned_sampled)
```

## Using lasso regression for feature selection
```{r}
predictors = model.matrix(price~., data = data_cleaned_sampled)
response = data_cleaned_sampled$price
lasso = glmnet(predictors, response, alpha = 6)
cv.lasso = cv.glmnet(predictors, response, alpha = 6)

plot(lasso, xvar = "lambda")
```


